### ISSUE TITLE
How to set  own's COCOAPI

### ISSUE THREAD

**Issue by sanmulab** [twangnh/SimCal#5]
Hello author, thank you for your work. Regarding the experimental results on COCO_lt, I would like to know how to change the evaluation API to get experimental results such as AP1, AP2, AP3, and AP4. My code base is based on mmdet=2.3.0. Look forward to your reply!

**Comment by twangnh** [comment]
Hi, you can check the two files (coco.py and cocoeval.py) for reference, or try replacing them in the cocoapi
[coco.zip](https://github.com/twangnh/SimCal/files/7811701/coco.zip)

**Comment by sanmulab** [comment]
Thanks for the author's reply. Is the setting of the coco code you provided the same as the setting of the paper result? Can I directly replace it or need to modify it?

**Comment by twangnh** [comment]
Yes, it is the paper's setting, it should be ok to directly replace it.

**Comment by sanmulab** [comment]
I have installed pycocotools, and then try to replace coco.py and cocoeval.py in the pycocotools folder in the environment. But the following error is reported: AttributeError:'COCO' object has no attribute'get_cat_ids'. I don't know if there is a problem with my operation.

**Comment by twangnh** [comment]
the pycocotools you are using may not be compatible with the py file ( the function is named getCatIds in the provided file), please try pycocotools with lower version

**Comment by sanmulab** [comment]
For the last question, I found the following code in the coco.py file you provided:
import pickle
        pickle.dump(y, open('./y.pkl', 'wb'))
        ## calculate sample num for each class
        y_sample = y.copy()
        for i, num in enumerate(y):
            if i<20:
                y_sample[i] = y[i]
            elif i>=20 and i<40:
                y_sample[i] = random.randint(800, 8000)
                while y_sample[i]>y[i]:
                    y_sample[i] = random.randint(800, 8000)
                # print(y_sample[i])
            elif i>=40 and i<60:
                y_sample[i] = random.randint(80, 800)
                # print(y_sample[i])
            elif i>=60 and i<80:
                y_sample[i] = random.randint(8, 80)
                # print(y_sample[i])

Must this y.pkl file be included?

**Comment by sanmulab** [comment]
The problem has been solved, thank you!
